apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-devops-helm-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-devops-helm-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-devops-helm-app.name" . }}
    spec:
      containers:
        - name: my-devops-helm-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5